server:
  port: 80
  
spring:  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true    
  h2:
    console:
      enabled: true
      path: /h2-console   
    
xtenant:
  citi:
    datasource:
      driverClassName: org.h2.Driver  
      jdbcUrl: jdbc:h2:file:c://database/data/citidb
      username: citi
      password: citi-secret
  cibc:
    datasource:
      driverClassName: org.h2.Driver
      jdbcUrl: jdbc:h2:file:c://database/data/cibcdb
      username: cibc
      password: cibc-secret 
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      access-token:
        expiration: 86400000 # a day
      refreshToken:
        expiration: 604800000 # 7 days   
